### ISSUE TITLE
Handle redundancy in "news and events" between ehcache.org and terracotta.org

### ISSUE THREAD

**Issue by jhouserizer** [Terracotta-OSS/terracotta.org-site#5]
... Either:

1- produce automation to make them equivalent  (edit one, and the other pics up the changes)

2- settle on the content being one site only, and have the other site link to it.

**Comment by jhouserizer** [comment]
existing news and events https://github.com/ehcache/ehcache.org-site/blob/master/events/index.md

**Comment by akomakom** [comment]
Will make module terracotta-oss/terracotta.org-site-events to share events for both site publishers.

**Comment by akomakom** [comment]
This is done for tc and waiting on a PR approval for ehcache.

Moved the events/ subdir from ehcache.org-site to its own module (history preserved).  Removed it from terracotta.org-site, now the jenkins job pulls it.   Made a similar PR for ehcache, currently open.  

(Also changed the menu id's so that navigation highlighting works)
